logging:
  level:
    root: INFO
    no.shj.payment.ruleengine: DEBUG

spring:
  cloud:
    azure:
      cosmos:
        endpoint: https://rule-configuration-cosmos-db.documents.azure.com:443/
        key: ${COSMOS_DB_KEY} # will be set in the deploy pipeline from github secrets
        database: rule-configuration-db