# Rule Engine Application Settings
rules:
  infrastructure:
    cache:
      evictiontimeinseconds: 60

logging:
  level:
    root: INFO
    no.shj.payment.ruleengine: DEBUG

spring:
  cloud:
    azure:
      cosmos:
        endpoint: https://rule-configuration-cosmos-db.documents.azure.com:443/
        database: rule-configuration-db
        # Key will be set by deploy pipeline from GitHub Secrets
        key: notUsedSetInGithubSecrets
