name: Deploy infra - trigger when needed.

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        type: string
        required: false
  push:
    branches:
      - main
    paths:
      - '.deploy/**'  # Trigger only if changes are made to files in the .deploy folder

env:
  RESOURCE_GROUP_NAME: payment-engine-preprod

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - name: Deploy bicep
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az deployment sub create --location 'norwayeast' --template-file ./.deploy/main.bicep
