name: Deploy infra - trigger when needed.

on:
  push:
    branches:
      - main
    paths:
      - '.deploy/**'  # Trigger only if changes are made to files in the .deploy folder

env:
  RESOURCE_GROUP_NAME: payment-engine-preprod

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - name: Setup Azure CLI
        uses: azure/setup-azure-cli@v1
        with:
          azure-cli-version: 'latest'
      - name: Deploy Main Bicep File
        run: |
          az deployment group create \
          --resource-group ${{ env.RESOURCE_GROUP_NAME }}
          --template-file ./deploy/main.bicep
          --parameters @parameters.json
